In [2]:
import pandas as pd 
import numpy as np

In [19]:
df1 = pd.read_csv('details_of_assembly_segment_2019_mod.csv')
df1

,state_name,parlimentary_constituency_name,assembly_constituency_name,nota_votes,candidate_name,party_name,votes_secured,assembly_constituency_number,total_votes_in_state,parliament_constituency_number,total_voters
0,Andhra Pradesh,Aruku,Palakonda (ST),3736,KISHORE CHANDRA DEO,TDP,54056.0,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Aruku,Palakonda (ST),3736,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,BJP,1753.0,NaN,NaN,NaN,NaN
2,Andhra Pradesh,Aruku,Palakonda (ST),3736,GODDETI. MADHAVI,YSRCP,69588.0,NaN,NaN,NaN,NaN
3,Andhra Pradesh,Aruku,Palakonda (ST),3736,SHRUTI DEVI VYRICHERLA,INC,1327.0,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Aruku,Palakonda (ST),3736,GANGULAIAH VAMPURU.,JnP,2987.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
58920,Puducherry,Puducherry,Yanam,314,N. TAMIZH MARANE,IND,62.0,NaN,NaN,NaN,NaN
58921,Puducherry,Puducherry,Yanam,314,TIRAVITAMANKAI@LOURDHUMARY,IND,14.0,NaN,NaN,NaN,NaN
58922,Puducherry,Puducherry,Yanam,314,IMS. BALAJI,IND,65.0,NaN,NaN,NaN,NaN
58923,Puducherry,Puducherry,Yanam,314,RAMESH.D,IND,77.0,NaN,NaN,NaN,NaN
58924,Puducherry,Puducherry,Yanam,314,V. RAMAMURTHI,IND,26.0,NaN,NaN,NaN,NaN

In [21]:
nan_columns = df1.columns[df1.isna().any()].tolist()
print(f"Columns with NaN values: {nan_columns}")

Columns with NaN values: ['votes_secured', 'assembly_constituency_number', 'total_votes_in_state', 'parliament_constituency_number', 'total_voters']

In [23]:
print(df1[df1.isna().any(axis=1)])

           state_name parlimentary_constituency_name  \
0      Andhra Pradesh                         Aruku
1      Andhra Pradesh                         Aruku
2      Andhra Pradesh                         Aruku
3      Andhra Pradesh                         Aruku
4      Andhra Pradesh                         Aruku
...               ...                            ...
58920      Puducherry                     Puducherry
58921      Puducherry                     Puducherry
58922      Puducherry                     Puducherry
58923      Puducherry                     Puducherry
58924      Puducherry                     Puducherry

      assembly_constituency_name  nota_votes  \
0                 Palakonda (ST)        3736
1                 Palakonda (ST)        3736
2                 Palakonda (ST)        3736
3                 Palakonda (ST)        3736
4                 Palakonda (ST)        3736
...                          ...         ...
58920                      Yanam         314
58921                      Yanam         314
58922                      Yanam         314
58923                      Yanam         314
58924                      Yanam         314

                                          candidate_name party_name  \
0                                    KISHORE CHANDRA DEO        TDP
1      Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...        BJP
2                                       GODDETI. MADHAVI      YSRCP
3                                 SHRUTI DEVI VYRICHERLA        INC
4                                    GANGULAIAH VAMPURU.        JnP
...                                                  ...        ...
58920                                   N. TAMIZH MARANE        IND
58921                         TIRAVITAMANKAI@LOURDHUMARY        IND
58922                                        IMS. BALAJI        IND
58923                                           RAMESH.D        IND
58924                                      V. RAMAMURTHI        IND

       votes_secured  assembly_constituency_number  total_votes_in_state  \
0            54056.0                           NaN                   NaN
1             1753.0                           NaN                   NaN
2            69588.0                           NaN                   NaN
3             1327.0                           NaN                   NaN
4             2987.0                           NaN                   NaN
...              ...                           ...                   ...
58920           62.0                           NaN                   NaN
58921           14.0                           NaN                   NaN
58922           65.0                           NaN                   NaN
58923           77.0                           NaN                   NaN
58924           26.0                           NaN                   NaN

       parliament_constituency_number  total_voters
0                                 NaN           NaN
1                                 NaN           NaN
2                                 NaN           NaN
3                                 NaN           NaN
4                                 NaN           NaN
...                               ...           ...
58920                             NaN           NaN
58921                             NaN           NaN
58922                             NaN           NaN
58923                             NaN           NaN
58924                             NaN           NaN

[58925 rows x 11 columns]

In [8]:
df2 = pd.read_csv('eci_data_2024.csv', encoding='ISO-8859-1')
df2

,S.N,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,State,Constituency
0,1,BISHNU PADA RAY,Bharatiya Janata Party,102182,254,102436,50.58,Andaman & Nicobar Islands,Andaman & Nicobar Islands - 1
1,2,KULDEEP RAI SHARMA,Indian National Congress,77829,211,78040,38.54,Andaman & Nicobar Islands,Andaman & Nicobar Islands - 1
2,3,MANOJ PAUL,Andaman Nicobar Democratic Congress,8236,18,8254,4.08,Andaman & Nicobar Islands,Andaman & Nicobar Islands - 1
3,4,D AYYAPPAN,Communist Party of India (Marxist),6009,8,6017,2.97,Andaman & Nicobar Islands,Andaman & Nicobar Islands - 1
4,5,V.K. ABDUL AZIZ,Independent,2195,8,2203,1.09,Andaman & Nicobar Islands,Andaman & Nicobar Islands - 1
...,...,...,...,...,...,...,...,...,...
8897,9,SK. SAPIYAR ALI,Independent,2924,-,2924,0.21,West Bengal,Uluberia - 26
8898,10,NIKHIL BERA,Socialist Unity Centre Of India (COMMUNIST),2095,12,2107,0.15,West Bengal,Uluberia - 26
8899,11,AMAL KUMAR BARMAN,Independent,1997,3,2000,0.14,West Bengal,Uluberia - 26
8900,12,RAMPRASAD GHORAI,Indian Unity Centre,1568,4,1572,0.11,West Bengal,Uluberia - 26
8901,13,NOTA,None of the Above,11263,55,11318,0.81,West Bengal,Uluberia - 26

In [9]:
df3 = pd.read_csv('maha_results_2019.csv')
df3

,STATE/UT NAME,AC NO.,AC NAME,CANDIDATE NAME,SEX,AGE,CATEGORY,PARTY,SYMBOL,GENERAL,POSTAL,TOTAL,% VOTES POLLED,TOTAL ELECTORS
0,Maharashtra,1,Akkalkuwa,1 ADV. K. C. PADAVI,MALE,61.0,ST,INC,Hand,82509,261.0,82770,41.255458,278888.0
1,Maharashtra,1,Akkalkuwa,2 AAMSHYA FULJI PADAVI,MALE,51.0,ST,SHS,Bow and Arrow,80532,142.0,80674,40.210738,278888.0
2,Maharashtra,1,Akkalkuwa,3 NAGESH DILVARSING PADVI,MALE,44.0,ST,IND,Gas Stove,21583,81.0,21664,10.798094,278888.0
3,Maharashtra,1,Akkalkuwa,4 NOTA,NaN,NaN,NaN,NOTA,NOTA,4856,1.0,4857,2.420898,278888.0
4,Maharashtra,1,Akkalkuwa,5 ADV. KAILAS PRATAPSING VASAVE,MALE,28.0,ST,AAAP,Broom,4034,21.0,4055,2.021154,278888.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3808,Maharashtra,288,Jath,6 Mahadev Harishchandra Kamble,MALE,38.0,SC,BSP,Elephant,1507,14.0,1521,0.867037,272345.0
3809,Maharashtra,288,Jath,7 NOTA,NaN,NaN,NaN,NOTA,NOTA,1085,1.0,1086,0.619068,272345.0
3810,Maharashtra,288,Jath,8 Krishndev Dhondiram Gayakavad,MALE,63.0,GENERAL,JD(S),A lady farmer carrying paddy on her head,576,4.0,580,0.330626,272345.0
3811,Maharashtra,288,Jath,9 SriVenkateshwar Maha Swamiji (Katakadhond D. G),MALE,32.0,SC,HJP,Tractor Chalata Kissan,452,1.0,453,0.258230,272345.0
3812,TURNOUT,TOTAL :,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173924,1501.0,175425,64.412785,NaN